### PR TITLE
[WIP] Dedicated update script and other improvements

### PR DESCRIPTION
**Pull request by exploide**
This PR does a couple of things, feel free to accept, discuss, reject or cherry-pick. If we agree on doing something not, I can revert (and maybe force push).

This is subject to change as I will continue with database support now. You may however merge at any time and I can submit further commits in new PRs.

See commit messages for details on what I did.

What I didn't get so far: You are using a geo library but then there are several own geometry related functions. Maybe the library can be used to generate the centroid?! Or can we get rid of it? (It's used only one time?!) Also, I'm not sure why some other dependencies are present in the vendor folder.

### CODE REVIEW

**Comment by exploide** [comment]
Note: triggering the update from the web is still possible. Just access `/update.php`. We might restrict the access later...

**Comment by ENT8R** [comment]
I will merge it now so I can also continue to develop.

> Maybe the library can be used to generate the centroid?!

The library offers a method to get the centroid of a geometry but the point does not have to be on the line itself... This is why I didn't use that method.

> Or can we get rid of it? (It's used only one time?!)

I think it is not used only one time. The function which uses the most of this library is the `get_centroid` method. And it is used to convert the `LINESTRING` geometry to a geometry one can work with.
But maybe we don't need the whole library but only the files which are necessary for this program.

> Also, I'm not sure why some other dependencies are present in the vendor folder.

I will take a look at it and see if we really need all of them!

**Comment by exploide** [comment]
> The library offers a method to get the centroid of a geometry but the point does not have to be on the line itself... This is why I didn't use that method.

I thought it is expected that the centroid not necessarily lies on the line. /cc @westnordost ?

> But maybe we don't need the whole library but only the files which are necessary for this program.
Ok. On the other hand, I consider it kind of ugly to copy files from other projects directly into this repository. I would ignore the vendor folder in .gitignore and let the user/admin execute composer on deployment. However, your choice here.

**Comment by ENT8R** [comment]
> I would ignore the vendor folder in .gitignore and let the user/admin execute composer on deployment

The library I used had some issues I had to resolve myself this is why I included the `vendor` folder. Otherwise I would have done it like that...

**Pull request merged**
